## Cargar datos con la funcion read_csv

In [1]:
import pandas as pd
import os
import numpy as np
os.getcwd()

'C:\\Users\\USER\\OneDrive\\Documentos\\GitHub\\python-ml-course\\notebooks_propios'

In [2]:
mainpath = r"\Users\USER\OneDrive\Documentos\GitHub\python-ml-course\datasets"
filename = r"titanic\titanic3.csv"
fullpath = mainpath + "\\" + filename
fullpath2 = os.path.join(mainpath,filename)

In [ ]:
data2 = pd.read_csv(fullpath2)
data2.head()

In [ ]:
data = pd.read_csv(r"..\datasets\titanic\titanic3.csv")

En el caso de trabajar con windows se le debe agregar la letra "r" antes de colocar la ruta, de lo contrario da un error, puede que este relacionado a las ultimas actualizaciones que le han hecho a python.

In [ ]:
data.head()

## Ejemplos de los parametros de la funcion pd.read_csv

pd.read_csv(filepath = r"..\datasets\chopsticks\chopstick-effectiveness.csv")

In [ ]:
data2 = pd.read_csv(mainpath + "\\" + r"customer-churn-model\Customer Churn Model.txt")
data2.head()

In [ ]:
data2.columns.values

In [ ]:
data_cols = pd.read_csv(mainpath + "\\" + r"customer-churn-model\Customer Churn Columns.csv")
data_col_list = data_cols["Column_Names"].tolist()

In [ ]:
data2 = pd.read_csv(mainpath + "\\" + r"customer-churn-model\Customer Churn Model.txt", header = None, names = data_col_list)
data2.head()

### Explicacion del codigo para futuras referencias

A veces los nombres de las columnas vienen en archivos distintos a los valores, por lo que tenemos que agregarlos de manera manual, para la cual se leen los valores, se convierten en una lista.

Dentro de la fundion pd.read_csv se debe poner el  parametro header como None para que ignore los nombres de la columna y posteriormente agregar en name los nombres de las columnas obtenidos.

## Carga de datos a través de la función open

Open es muy bueno cuando el dataset es muy grande

In [ ]:
data3 = open(mainpath + "\\" + r"customer-churn-model\Customer Churn Model.txt","r")

In [ ]:
cols = next(data3).strip().split(",")
n_cols = len(cols)

In [ ]:
counter = 0
main_dict = {}
for col in cols:
    main_dict[col] = []

In [ ]:
counter = 0
for line in data3:
    values = line.strip().split(",")
    for i in range(len(cols)):
        main_dict[cols[i]].append(values[i])
    counter += 1

print ("El dataset tiene %d filas y %d columnas" % (counter,n_cols))

## Explicacion del codigo

Tomo los valores de la primera fila, elimino los espacios en blancos y caracteres especiales  usando el metodo .strip(), luego separo por "," usando split(","). 

Recorro columna a columna llenando cada uno de los espacios vacios del directorio para esa fila, luego paso a la siguiente linea.

In [ ]:
df3 = pd.DataFrame(main_dict)
df3.head()

## Escritura

In [ ]:
infile = mainpath + "\\" + r"customer-churn-model\Customer Churn Model.txt"
outfile = mainpath + "\\" + r"customer-churn-model\Tab Customer Churn Model.txt"

In [ ]:
with open(infile,"r") as infile1:
    with open(outfile,"w") as outfile1:
        for line in infile1:
            files = line.strip().split(",")
            outfile1.write("\t".join(files) + "\n")

In [ ]:
data4 = pd.read_csv(outfile, sep = "\t")
data4.head()

# Leer datos desde una URL externa

In [3]:
olympics_url = "https://raw.githubusercontent.com/brandomr/olympics/refs/heads/master/winterolympics.csv"

In [4]:
medals_data = pd.read_csv(olympics_url)
medals_data.shape

(21, 9)

In [5]:
import csv
from urllib.request import urlopen

In [6]:
response = urlopen("https://raw.githubusercontent.com/brandomr/olympics/refs/heads/master/winterolympics.csv")
response

## Otro metodo de carga usando urllib3 de acuerdo a la documentacion oficial

In [7]:
import urllib3
http = urllib3.PoolManager()
r = http.request('GET',olympics_url)
r.status
data = r.data
data

b"Year,City,Country,Countries,Participants,Men,Women,Sports,Events\n2010,Vancouver,Canada,82,2577,1527,1050,15,86\n2006,Torino,Italy,79,2518,1556,962,15,84\n2002,Salt Lake City,United States,79,2432,1533,899,15,78\n1998,Nagano,Japan,72,2209,1414,795,14,68\n1994,Lillehammer,Norway,67,1765,1232,533,12,61\n1992,Albertville,France,64,2031,1447,584,14,57\n1988,Calgary,Canada,57,1681,1269,412,13,46\n1984,Sarajevo,Yugoslavia,49,1306,1025,281,10,39\n1980,Lake Placid,United States,37,1081,843,238,10,38\n1976,Innsbruck,Austria,37,1134,903,231,10,37\n1972,Sapporo,Japan,35,1024,817,207,10,35\n1968,Grenoble,France,37,1188,965,223,10,35\n1964,Innsbruck,Austria,36,1196,995,201,11,34\n1960,Squaw Valley,United States,30,670,525,145,8,27\n1956,Cortina d'Ampezzo,Italy,32,833,698,135,8,24\n1952,Oslo,Norway,30,734,624,110,9,22\n1948,Sankt Moritz,Switzerland,28,730,650,80,11,22\n1936,Garmisch-Partenkirchen,Germany,28,889,774,115,10,17\n1932,Lake Placid,United States,17,378,344,34,9,14\n1928,Sankt Moritz,Switzerland,26,516,488,28,10,13\n1924,Chamonix,France,20,376,360,16,10,17"

In [13]:
data = r.data.decode("utf-8")
print(type(data))
cols = data.split("\n")[0].split(",")
n_cols = len(cols)
cols

<class 'str'>

['Year',
 'City',
 'Country',
 'Countries',
 'Participants',
 'Men',
 'Women',
 'Sports',
 'Events']

In [14]:
main_dict = {}
for col in cols:
    main_dict[col] = []
main_dict

{'Year': [],
 'City': [],
 'Country': [],
 'Countries': [],
 'Participants': [],
 'Men': [],
 'Women': [],
 'Sports': [],
 'Events': []}

In [15]:
data.split("\n")[1].strip().split(",")

['2010', 'Vancouver', 'Canada', '82', '2577', '1527', '1050', '15', '86']

In [16]:
counter = 0
lines = data.strip().split("\n")
for line in lines:
    values = line.split(",")
    for i in range(len(cols)):
        main_dict[cols[i]].append(values[i])
    counter += 1
print("Este dataset tiene %d filas y %d" % (counter,n_cols))

Este dataset tiene 22 filas y 9

In [21]:
for key in main_dict:
    print(key, len(main_dict[key]))

Year 22
City 22
Country 22
Countries 22
Participants 22
Men 22
Women 22
Sports 22
Events 22

'Events'

In [22]:
df3 = pd.DataFrame(main_dict)
df3.head()

,Year,City,Country,Countries,Participants,Men,Women,Sports,Events
0,Year,City,Country,Countries,Participants,Men,Women,Sports,Events
1,2010,Vancouver,Canada,82,2577,1527,1050,15,86
2,2006,Torino,Italy,79,2518,1556,962,15,84
3,2002,Salt Lake City,United States,79,2432,1533,899,15,78
4,1998,Nagano,Japan,72,2209,1414,795,14,68

## Ficheros XLS y XLSX

In [ ]:
mainpath = r"\Users\USER\OneDrive\Documentos\GitHub\python-ml-course\datasets"
filename1 = r"titanic\titanic3.xls"
filename2 = r"titanic\titanic3.xlsx"

In [ ]:
titanic2 = pd.read_excel(mainpath + "\\" + filename1)
titanic3 = pd.read_excel(mainpath + "\\" + filename2)

Lo mas general es un read table

In [ ]:
titanic3.to_csv(mainpath + "\\titanic\\titanic_custom.csv")

In [ ]:
titanic3.to_excel(mainpath + "\\titanic\\titanic_custom.xlsx")

In [ ]:
titanic3.to_json(mainpath + "\\titanic\\titanic_custom.json")

### Descargar y procesar datos desde una URL externa (Completo)

In [67]:
# Obtencion de la direccion URL
olympics_url = "https://raw.githubusercontent.com/brandomr/olympics/refs/heads/master/winterolympics.csv"
# Ejercicio completo
import urllib3
http = urllib3.PoolManager()
r = http.request('GET',olympics_url)
print("El status de la respuesta es: %d" % (r.status))
response = r.data

# El objeto response contiene un string binario, asi que lo convertimos a un string descodificandolo en UTF-8
str_data = response.decode('utf-8')

# Dividimos el string en un array de filas, separandolo por intros
lines = str_data.split("\n")

# La primera linea contiene la cabecera asi que la estraemos
col_names = lines[0].split(",")

#Generamos un diccionario vacio donde ira la informacion procesada desde la URL externa
counter = 0
main_dict = {}
for col in col_names:
    main_dict[col] = []

# Procesamos fila a fila la informacion para ir rellenando el diccionario con los datos como hicimos antes
for line in lines:
    # Nos saltamos la primera linea que es la que contiene la cabecera
    if(counter > 0):
        # Separamos por comas y limpiamos espacios en blanco 
        values = line.strip().split(",")
        # Se anade cada valor a su respectiva columna del diccionario
        for i in range(len(col_names)):
            main_dict[col_names[i]].append(values[i])
    counter += 1

print("El numero de filas %d y el numero de columnas %d " % (counter,len(col_names)))

# Convertir de un dataframe
medals_df = pd.DataFrame(main_dict)

# seleccionar donde guardar el dataframe creado 
mainpath = r"C:\Users\USER\OneDrive\Documentos\GitHub\python-ml-course\\"
filepath = r"notebooks_propios\Datasets_generados\medals_df"
fullpath = os.path.join(mainpath,filepath)

# Lo guardamos en diferentes formatos
medals_df.to_csv(fullpath+".csv")
medals_df.to_json(fullpath+".json")
medals_df.to_excel(fullpath+".xlsx")

El status de la respuesta es: 200
El numero de filas 22 y el numero de columnas 9

## Crear una funcion para hacer esto generico

In [80]:
def downloadFromURL(url,filename,sep = ",",delim = "\n",encoding = 'utf-8'):
    # Obtencion de la direccion URL
    olympics_url = "https://raw.githubusercontent.com/brandomr/olympics/refs/heads/master/winterolympics.csv"
    # Ejercicio completo
    import urllib3
    http = urllib3.PoolManager()
    r = http.request('GET',url)
    print("El status de la respuesta es: %d" % (r.status))
    response = r.data
    
    # El objeto response contiene un string binario, asi que lo convertimos a un string descodificandolo en UTF-8
    str_data = response.decode('utf-8')
    
    # Dividimos el string en un array de filas, separandolo por intros
    lines = str_data.split(delim)
    
    # La primera linea contiene la cabecera asi que la estraemos
    col_names = lines[0].split(sep)
    
    #Generamos un diccionario vacio donde ira la informacion procesada desde la URL externa
    counter = 0
    main_dict = {}
    for col in col_names:
        main_dict[col] = []
    
    # Procesamos fila a fila la informacion para ir rellenando el diccionario con los datos como hicimos antes
    for line in lines:
        # Nos saltamos la primera linea que es la que contiene la cabecera
        if(counter > 0):
            # Separamos por comas y limpiamos espacios en blanco 
            values = line.strip().split(sep)
            # Se anade cada valor a su respectiva columna del diccionario
            for i in range(len(col_names)):
                main_dict[col_names[i]].append(values[i])
        counter += 1
    
    print("El numero de filas %d y el numero de columnas %d " % (counter,len(col_names)))
    
    # Convertir de un dataframe
    df = pd.DataFrame(main_dict)
    
    # seleccionar donde guardar el dataframe creado 
    mainpath = r"C:\Users\USER\OneDrive\Documentos\GitHub\python-ml-course\notebooks_propios\Datasets_generados\\"
    #filename = r"notebooks_propios\Datasets_generados\\"
    fullpath = os.path.join(mainpath,filename)
    
    # Lo guardamos en diferentes formatos
    df.to_csv(fullpath+".csv")
    df.to_json(fullpath+".json")
    df.to_excel(fullpath+".xlsx")
    return df

In [82]:
medals_df = downloadFromURL(olympics_url,"Atletas",sep = ",",delim = "\n")
medals_df.head()

El status de la respuesta es: 200
El numero de filas 22 y el numero de columnas 9

,Year,City,Country,Countries,Participants,Men,Women,Sports,Events
0,2010,Vancouver,Canada,82,2577,1527,1050,15,86
1,2006,Torino,Italy,79,2518,1556,962,15,84
2,2002,Salt Lake City,United States,79,2432,1533,899,15,78
3,1998,Nagano,Japan,72,2209,1414,795,14,68
4,1994,Lillehammer,Norway,67,1765,1232,533,12,61