## Cargar datos con la funcion read_csv

In [14]:
import pandas as pd
import os
import numpy as np
os.getcwd()

'C:\\Users\\USER\\OneDrive\\Documentos\\GitHub\\python-ml-course\\notebooks_propios'

In [3]:
mainpath = r"\Users\USER\OneDrive\Documentos\GitHub\python-ml-course\datasets"
filename = r"titanic\titanic3.csv"
fullpath = mainpath + "\\" + filename
fullpath2 = os.path.join(mainpath,filename)

In [17]:
data2 = pd.read_csv(fullpath2)
data2.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [4]:
data = pd.read_csv(r"..\datasets\titanic\titanic3.csv")

En el caso de trabajar con windows se le debe agregar la letra "r" antes de colocar la ruta, de lo contrario da un error, puede que este relacionado a las ultimas actualizaciones que le han hecho a python.

In [7]:
data.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

## Ejemplos de los parametros de la funcion pd.read_csv

pd.read_csv(filepath = r"..\datasets\chopsticks\chopstick-effectiveness.csv")

In [20]:
data2 = pd.read_csv(mainpath + "\\" + r"customer-churn-model\Customer Churn Model.txt")
data2.head()

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False.
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False.
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False.
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False.
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False.

In [22]:
data2.columns.values

array(['State', 'Account Length', 'Area Code', 'Phone', "Int'l Plan",
       'VMail Plan', 'VMail Message', 'Day Mins', 'Day Calls',
       'Day Charge', 'Eve Mins', 'Eve Calls', 'Eve Charge', 'Night Mins',
       'Night Calls', 'Night Charge', 'Intl Mins', 'Intl Calls',
       'Intl Charge', 'CustServ Calls', 'Churn?'], dtype=object)

In [31]:
data_cols = pd.read_csv(mainpath + "\\" + r"customer-churn-model\Customer Churn Columns.csv")
data_col_list = data_cols["Column_Names"].tolist()

In [33]:
data2 = pd.read_csv(mainpath + "\\" + r"customer-churn-model\Customer Churn Model.txt", header = None, names = data_col_list)
data2.head()

,A,B,C,D,E,F,G,H,I,J,...,L,M,N,O,P,Q,R,S,T,U
0,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
1,KS,128,415,382-4657,no,yes,25,265.100000,110,45.070000,...,99,16.780000,244.700000,91,11.010000,10.000000,3,2.700000,1,False.
2,OH,107,415,371-7191,no,yes,26,161.600000,123,27.470000,...,103,16.620000,254.400000,103,11.450000,13.700000,3,3.700000,1,False.
3,NJ,137,415,358-1921,no,no,0,243.400000,114,41.380000,...,110,10.300000,162.600000,104,7.320000,12.200000,5,3.290000,0,False.
4,OH,84,408,375-9999,yes,no,0,299.400000,71,50.900000,...,88,5.260000,196.900000,89,8.860000,6.600000,7,1.780000,2,False.

### Explicacion del codigo para futuras referencias

A veces los nombres de las columnas vienen en archivos distintos a los valores, por lo que tenemos que agregarlos de manera manual, para la cual se leen los valores, se convierten en una lista.

Dentro de la fundion pd.read_csv se debe poner el  parametro header como None para que ignore los nombres de la columna y posteriormente agregar en name los nombres de las columnas obtenidos.

## Carga de datos a través de la función open

Open es muy bueno cuando el dataset es muy grande

In [89]:
data3 = open(mainpath + "\\" + r"customer-churn-model\Customer Churn Model.txt","r")

In [90]:
cols = next(data3).strip().split(",")
n_cols = len(cols)

In [91]:
counter = 0
main_dict = {}
for col in cols:
    main_dict[col] = []

In [94]:
counter = 0
for line in data3:
    values = line.strip().split(",")
    for i in range(len(cols)):
        main_dict[cols[i]].append(values[i])
    counter += 1

print ("El dataset tiene %d filas y %d columnas" % (counter,n_cols))

El dataset tiene 0 filas y 21 columnas

## Explicacion del codigo

Tomo los valores de la primera fila, elimino los espacios en blancos y caracteres especiales  usando el metodo .strip(), luego separo por "," usando split(","). 

Recorro columna a columna llenando cada uno de los espacios vacios del directorio para esa fila, luego paso a la siguiente linea.

In [93]:
df3 = pd.DataFrame(main_dict)
df3.head()

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,KS,128,415,382-4657,no,yes,25,265.100000,110,45.070000,...,99,16.780000,244.700000,91,11.010000,10.000000,3,2.700000,1,False.
1,OH,107,415,371-7191,no,yes,26,161.600000,123,27.470000,...,103,16.620000,254.400000,103,11.450000,13.700000,3,3.700000,1,False.
2,NJ,137,415,358-1921,no,no,0,243.400000,114,41.380000,...,110,10.300000,162.600000,104,7.320000,12.200000,5,3.290000,0,False.
3,OH,84,408,375-9999,yes,no,0,299.400000,71,50.900000,...,88,5.260000,196.900000,89,8.860000,6.600000,7,1.780000,2,False.
4,OK,75,415,330-6626,yes,no,0,166.700000,113,28.340000,...,122,12.610000,186.900000,121,8.410000,10.100000,3,2.730000,3,False.

## Escritura

In [4]:
infile = mainpath + "\\" + r"customer-churn-model\Customer Churn Model.txt"
outfile = mainpath + "\\" + r"customer-churn-model\Tab Customer Churn Model.txt"

In [9]:
with open(infile,"r") as infile1:
    with open(outfile,"w") as outfile1:
        for line in infile1:
            files = line.strip().split(",")
            outfile1.write("\t".join(files) + "\n")

In [12]:
data4 = pd.read_csv(outfile, sep = "\t")
data4.head()

,State,Account Length,Area Code,Phone,Int'l Plan,VMail Plan,VMail Message,Day Mins,Day Calls,Day Charge,...,Eve Calls,Eve Charge,Night Mins,Night Calls,Night Charge,Intl Mins,Intl Calls,Intl Charge,CustServ Calls,Churn?
0,KS,128,415,382-4657,no,yes,25,265.1,110,45.07,...,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False.
1,OH,107,415,371-7191,no,yes,26,161.6,123,27.47,...,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False.
2,NJ,137,415,358-1921,no,no,0,243.4,114,41.38,...,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False.
3,OH,84,408,375-9999,yes,no,0,299.4,71,50.90,...,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False.
4,OK,75,415,330-6626,yes,no,0,166.7,113,28.34,...,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False.

# Leer datos desde una URL externa

In [13]:
olympics_url = "https://raw.githubusercontent.com/brandomr/olympics/refs/heads/master/winterolympics.csv"

In [18]:
medals_data = pd.read_csv(olympics_url)
medals_data.shape

(21, 9)

In [32]:
import csv
from urllib.request import urlopen

In [35]:
response = urlopen("https://raw.githubusercontent.com/brandomr/olympics/refs/heads/master/winterolympics.csv")
response

## Otro metodo de carga usando urllib3 de acuerdo a la documentacion oficial

In [103]:
import urllib3
http = urllib3.PoolManager()
r = http.request('GET',olympics_url)
r.status
data = r.data
data

b"Year,City,Country,Countries,Participants,Men,Women,Sports,Events\n2010,Vancouver,Canada,82,2577,1527,1050,15,86\n2006,Torino,Italy,79,2518,1556,962,15,84\n2002,Salt Lake City,United States,79,2432,1533,899,15,78\n1998,Nagano,Japan,72,2209,1414,795,14,68\n1994,Lillehammer,Norway,67,1765,1232,533,12,61\n1992,Albertville,France,64,2031,1447,584,14,57\n1988,Calgary,Canada,57,1681,1269,412,13,46\n1984,Sarajevo,Yugoslavia,49,1306,1025,281,10,39\n1980,Lake Placid,United States,37,1081,843,238,10,38\n1976,Innsbruck,Austria,37,1134,903,231,10,37\n1972,Sapporo,Japan,35,1024,817,207,10,35\n1968,Grenoble,France,37,1188,965,223,10,35\n1964,Innsbruck,Austria,36,1196,995,201,11,34\n1960,Squaw Valley,United States,30,670,525,145,8,27\n1956,Cortina d'Ampezzo,Italy,32,833,698,135,8,24\n1952,Oslo,Norway,30,734,624,110,9,22\n1948,Sankt Moritz,Switzerland,28,730,650,80,11,22\n1936,Garmisch-Partenkirchen,Germany,28,889,774,115,10,17\n1932,Lake Placid,United States,17,378,344,34,9,14\n1928,Sankt Moritz,Switzerland,26,516,488,28,10,13\n1924,Chamonix,France,20,376,360,16,10,17"

In [104]:
data = r.data.decode("utf-8")
print(type(data))
cols = data.split("\n")[0].split(",")
n_cols = len(cols)
cols

<class 'str'>

['Year',
 'City',
 'Country',
 'Countries',
 'Participants',
 'Men',
 'Women',
 'Sports',
 'Events']

In [105]:
main_dict = {}
for col in cols:
    main_dict[col] = []
main_dict

{'Year': [],
 'City': [],
 'Country': [],
 'Countries': [],
 'Participants': [],
 'Men': [],
 'Women': [],
 'Sports': [],
 'Events': []}

In [89]:
data.split("\n")[1].strip().split(",")

['2010', 'Vancouver', 'Canada', '82', '2577', '1527', '1050', '15', '86']

In [106]:
counter = 0
lines = data.strip().split("\n")
for line in lines:
    values = line.split(",")
    for i in range(len(cols)):
        main_dict[cols[i]].append(values[i])
    counter += 1
print("Este dataset tiene %d filas y %d" % (counter,n_cols))

Este dataset tiene 22 filas y 9

In [107]:
for key in main_dict:
    print(key, len(main_dict[key]))

Year 22
City 22
Country 22
Countries 22
Participants 22
Men 22
Women 22
Sports 22
Events 22

In [108]:
df3 = pd.DataFrame(main_dict)
df3.head()

,Year,City,Country,Countries,Participants,Men,Women,Sports,Events
0,Year,City,Country,Countries,Participants,Men,Women,Sports,Events
1,2010,Vancouver,Canada,82,2577,1527,1050,15,86
2,2006,Torino,Italy,79,2518,1556,962,15,84
3,2002,Salt Lake City,United States,79,2432,1533,899,15,78
4,1998,Nagano,Japan,72,2209,1414,795,14,68

## Ficheros XLS y XLSX

In [122]:
mainpath = r"\Users\USER\OneDrive\Documentos\GitHub\python-ml-course\datasets"
filename1 = r"titanic\titanic3.xls"
filename2 = r"titanic\titanic3.xlsx"

In [123]:
titanic2 = pd.read_excel(mainpath + "\\" + filename1)
titanic3 = pd.read_excel(mainpath + "\\" + filename2)

Lo mas general es un read table

In [127]:
titanic3.to_csv(mainpath + "\\titanic\\titanic_custom.csv")

In [129]:
titanic3.to_excel(mainpath + "\\titanic\\titanic_custom.xlsx")

In [130]:
titanic3.to_json(mainpath + "\\titanic\\titanic_custom.json")