# Agregacion de datos por categoria

In [2]:
import numpy as np
import pandas as pd

In [3]:
gender = ["Male","Female"]
income = ["Poor","Midle Class","Rich"]

In [4]:
n = 500
gender_data = []
income_data = []

for i in range(0,n):
    gender_data.append(np.random.choice(gender))
    income_data.append(np.random.choice(income))
income_data[0:10]

[np.str_('Poor'),
 np.str_('Rich'),
 np.str_('Poor'),
 np.str_('Midle Class'),
 np.str_('Midle Class'),
 np.str_('Rich'),
 np.str_('Midle Class'),
 np.str_('Poor'),
 np.str_('Rich'),
 np.str_('Rich')]

In [5]:
height = 160 + 30 * np.random.randn(n)
weight = 65 + 25 * np.random.randn(n)
age = np.ceil(30 + 12 * np.random.randn(n)).astype(int)
income = 18000 + 3500*np.random.randn(n)

In [8]:
data = pd.DataFrame(
    {
        'Gender': gender_data,
        'Economic Status': income_data,
        'Height': height,
        'Weight': weight,
        'Age': age,
        'Income': income
    }
)
data.head()

   Gender Economic Status      Height      Weight  Age        Income
0  Female            Poor  179.577883   68.312323   41  21823.733695
1  Female            Rich  172.575807  108.527119   39  16362.644164
2  Female            Poor  140.991421   42.049134   33  17398.793741
3  Female     Midle Class  171.716018   94.730666   21  15153.939483
4    Male     Midle Class  100.594870   76.320959    8  21013.488551

### Agrupacion de datos

In [17]:
grouped_gender = data.groupby("Gender")

In [18]:
grouped_gender.groups

{'Female': [0, 1, 2, 3, 5, 6, 7, 8, 9, 10, 16, 19, 21, 22, 23, 25, 27, 28, 29, 31, 33, 34, 36, 37, 39, 47, 49, 51, 54, 56, 57, 59, 60, 62, 63, 65, 67, 70, 71, 72, 78, 79, 81, 82, 86, 88, 89, 92, 93, 94, 95, 100, 101, 103, 104, 105, 107, 108, 109, 110, 114, 115, 117, 118, 119, 120, 121, 122, 124, 125, 129, 132, 134, 137, 140, 142, 143, 144, 146, 148, 152, 154, 155, 158, 162, 163, 164, 165, 171, 172, 173, 175, 176, 178, 179, 181, 182, 187, 188, 189, ...], 'Male': [4, 11, 12, 13, 14, 15, 17, 18, 20, 24, 26, 30, 32, 35, 38, 40, 41, 42, 43, 44, 45, 46, 48, 50, 52, 53, 55, 58, 61, 64, 66, 68, 69, 73, 74, 75, 76, 77, 80, 83, 84, 85, 87, 90, 91, 96, 97, 98, 99, 102, 106, 111, 112, 113, 116, 123, 126, 127, 128, 130, 131, 133, 135, 136, 138, 139, 141, 145, 147, 149, 150, 151, 153, 156, 157, 159, 160, 161, 166, 167, 168, 169, 170, 174, 177, 180, 183, 184, 185, 186, 190, 191, 192, 195, 196, 198, 200, 201, 202, 204, ...]}

In [13]:
for names, groups in grouped_gender:
    print(names)
    print(groups)

Female
     Gender Economic Status      Height      Weight  Age        Income
0    Female            Poor  179.577883   68.312323   41  21823.733695
1    Female            Rich  172.575807  108.527119   39  16362.644164
2    Female            Poor  140.991421   42.049134   33  17398.793741
3    Female     Midle Class  171.716018   94.730666   21  15153.939483
5    Female            Rich  153.299800   66.274915   30  16401.565024
..      ...             ...         ...         ...  ...           ...
487  Female     Midle Class  175.746323   83.031934   22  18528.987828
490  Female            Rich  124.370929   47.177036   27  10706.210397
494  Female     Midle Class  109.808471   75.001015   42  15979.638874
495  Female            Rich  178.706477   44.435548   23  20948.996860
498  Female            Poor  157.811506   -7.559344   22  16099.569138

[261 rows x 6 columns]
Male
    Gender Economic Status      Height      Weight  Age        Income
4     Male     Midle Class  100.594870   76.320959    8  21013.488551
11    Male            Poor  208.348939   84.103861   41  16933.604698
12    Male            Poor  119.627879   53.587712   42  19217.067002
13    Male            Rich  132.411867   84.532197   15  23611.268500
14    Male            Rich  119.861091   47.353411   37  15969.626554
..     ...             ...         ...         ...  ...           ...
492   Male     Midle Class   54.875214  119.636868   19  11964.601078
493   Male     Midle Class  142.041342   77.485503   43  15219.211268
496   Male            Poor  120.717068   49.779744   22  20075.074519
497   Male            Poor  110.723031  115.771175   55  20235.638982
499   Male            Poor  113.084879   41.203039   41  19168.970293

[239 rows x 6 columns]

In [14]:
grouped_gender.get_group("Female")

     Gender Economic Status      Height      Weight  Age        Income
0    Female            Poor  179.577883   68.312323   41  21823.733695
1    Female            Rich  172.575807  108.527119   39  16362.644164
2    Female            Poor  140.991421   42.049134   33  17398.793741
3    Female     Midle Class  171.716018   94.730666   21  15153.939483
5    Female            Rich  153.299800   66.274915   30  16401.565024
..      ...             ...         ...         ...  ...           ...
487  Female     Midle Class  175.746323   83.031934   22  18528.987828
490  Female            Rich  124.370929   47.177036   27  10706.210397
494  Female     Midle Class  109.808471   75.001015   42  15979.638874
495  Female            Rich  178.706477   44.435548   23  20948.996860
498  Female            Poor  157.811506   -7.559344   22  16099.569138

[261 rows x 6 columns]

In [19]:
double_group = data.groupby(["Gender","Economic Status"])

In [21]:
len(double_group)

6

In [23]:
for names, groups in double_group:
    print(names)
    print(groups)

(np.str_('Female'), np.str_('Midle Class'))
     Gender Economic Status      Height     Weight  Age        Income
3    Female     Midle Class  171.716018  94.730666   21  15153.939483
6    Female     Midle Class  205.488465  51.783604   40  22505.334070
19   Female     Midle Class  167.065779  84.519064   18  18644.316038
22   Female     Midle Class  148.112667  30.517556   34  22155.229381
29   Female     Midle Class  160.671739  23.588984   33  19381.323233
..      ...             ...         ...        ...  ...           ...
475  Female     Midle Class  197.589198  52.788249   49  25039.768815
476  Female     Midle Class  224.458480  75.711963   37  22470.222482
484  Female     Midle Class  165.727730  32.416843   36  17391.210540
487  Female     Midle Class  175.746323  83.031934   22  18528.987828
494  Female     Midle Class  109.808471  75.001015   42  15979.638874

[75 rows x 6 columns]
(np.str_('Female'), np.str_('Poor'))
     Gender Economic Status      Height     Weight  Age        Income
0    Female            Poor  179.577883  68.312323   41  21823.733695
2    Female            Poor  140.991421  42.049134   33  17398.793741
7    Female            Poor  151.526579  56.633413   40  23007.514800
21   Female            Poor  128.308905  41.590373   29  18429.902395
25   Female            Poor  173.817038  82.959145   34  24564.682865
..      ...             ...         ...        ...  ...           ...
463  Female            Poor  133.452099  67.401158   27  21564.443886
467  Female            Poor  158.369165  81.018572   18  18732.820887
482  Female            Poor  148.285488  65.502618   22  12591.571541
485  Female            Poor  166.123768  61.852452    3  19884.875125
498  Female            Poor  157.811506  -7.559344   22  16099.569138

[97 rows x 6 columns]
(np.str_('Female'), np.str_('Rich'))
     Gender Economic Status      Height      Weight  Age        Income
1    Female            Rich  172.575807  108.527119   39  16362.644164
5    Female            Rich  153.299800   66.274915   30  16401.565024
8    Female            Rich  105.694121   72.356038   28  16488.561579
9    Female            Rich  123.476310   93.303027   17  20142.349469
10   Female            Rich  183.737576   63.876618   36  18256.552782
..      ...             ...         ...         ...  ...           ...
462  Female            Rich  177.024929   29.919419   26  20241.760677
470  Female            Rich  131.698077   59.176714   21  24508.159164
483  Female            Rich  167.310302   66.949043   21  17737.738089
490  Female            Rich  124.370929   47.177036   27  10706.210397
495  Female            Rich  178.706477   44.435548   23  20948.996860

[89 rows x 6 columns]
(np.str_('Male'), np.str_('Midle Class'))
    Gender Economic Status      Height      Weight  Age        Income
4     Male     Midle Class  100.594870   76.320959    8  21013.488551
18    Male     Midle Class  190.745525   27.889522   29  11737.180801
41    Male     Midle Class  217.676980  109.200576    8  15853.051009
42    Male     Midle Class  124.490279   55.972358   36  19745.117115
50    Male     Midle Class  127.596097   28.779205   18  15271.083062
..     ...             ...         ...         ...  ...           ...
479   Male     Midle Class  168.830767   57.367632   45  17722.249867
486   Male     Midle Class  190.965395  126.567317   23  16771.923483
489   Male     Midle Class  150.591860   53.043085   30  16532.619558
492   Male     Midle Class   54.875214  119.636868   19  11964.601078
493   Male     Midle Class  142.041342   77.485503   43  15219.211268

[78 rows x 6 columns]
(np.str_('Male'), np.str_('Poor'))
    Gender Economic Status      Height      Weight  Age        Income
11    Male            Poor  208.348939   84.103861   41  16933.604698
12    Male            Poor  119.627879   53.587712   42  19217.067002
17    Male            Poor  141.637519   86.770931   33  26987.546172
24    Male            Poor  162.288336   42.985109   31  15850.616168
26    Male            Poor  135.146903   50.809795   25  15649.451901
..     ...             ...         ...         ...  ...           ...
488   Male            Poor  121.095442   63.465072   43  17433.406857
491   Male            Poor  184.973548   74.653035   28  22452.647725
496   Male            Poor  120.717068   49.779744   22  20075.074519
497   Male            Poor  110.723031  115.771175   55  20235.638982
499   Male            Poor  113.084879   41.203039   41  19168.970293

[87 rows x 6 columns]
(np.str_('Male'), np.str_('Rich'))
    Gender Economic Status      Height     Weight  Age        Income
13    Male            Rich  132.411867  84.532197   15  23611.268500
14    Male            Rich  119.861091  47.353411   37  15969.626554
15    Male            Rich  173.573270  64.889228   38  20209.451559
20    Male            Rich  168.494299  42.368655   26  19314.354109
30    Male            Rich  138.021010  74.770084   36   8723.123019
..     ...             ...         ...        ...  ...           ...
448   Male            Rich  149.736494  42.565584   26  19346.228613
457   Male            Rich  162.222130  39.640773   27  13150.211906
471   Male            Rich  145.381909  77.845596   36  21614.385388
477   Male            Rich  164.384330  53.356975   51  18949.088680
481   Male            Rich  111.652573  87.257544   18  19998.624166

[74 rows x 6 columns]